CREATE OR REPLACE VIEW pulse360_s4.bronze_smart_city.smart_city_signal_sample AS
SELECT *
FROM VALUES
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_singapore_smart_nation',
    'Singapore Smart Nation Urban Mobility',
    'SG',
    'Singapore',
    'city',
    'intelligent_parking',
    'Intelligent Parking and Curbside Intelligence',
    'municipal_open_data',
    'Singapore Smart Nation Public Reference',
    'sg_parking_smart_nation_public_001',
    'public_smart_parking_reference',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.88 AS DOUBLE),
    'Public smart-city reference explicitly includes smart parking, digital payments, and real-time guidance.',
    'https://www.smartnation.gov.sg/initiatives/smart-city-solutions/',
    'public',
    'Map mobility and parking stakeholders before proposing a CSP data-and-IoT extension.',
    to_json(named_struct('smart_city_domain', 'mobility', 'parking_signal', true, 'data_product_potential', true))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_singapore_smart_nation',
    'Singapore Smart Nation Urban Mobility',
    'SG',
    'Singapore',
    'city',
    'urban_data_brokerage',
    'Aggregated Mobility Insights and Data Brokerage',
    'mobility_data',
    'Singtel DataSpark Public Reference',
    'sg_dataspark_mobility_001',
    'anonymized_mobility_intelligence',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.84 AS DOUBLE),
    'Public reference describes anonymized mobility analysis for commuter planning.',
    'https://cdn.aws.singtel.com/annualreport/2015/business-review/group-digital-life/dataspark.html',
    'aggregated_anonymized',
    'Require privacy and data-governance review before activation.',
    to_json(named_struct('data_product', 'mobility_intelligence', 'requires_privacy_review', true))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_kuala_lumpur_mobility',
    'Kuala Lumpur Urban Mobility',
    'MY',
    'Malaysia',
    'city',
    'connected_city_iot_platform',
    'Smart City IoT Platform and Integrated Operations',
    'partner_ecosystem',
    'TM One Smart City Public Reference',
    'my_tmone_smart_city_001',
    'multi_domain_smart_city_portfolio',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.87 AS DOUBLE),
    'Portfolio references smart mobility, energy, surveillance, waste, infrastructure, environment, and digital governance.',
    'https://www.tmone.com.my/smart-services/smart-city/',
    'public',
    'Position connected-city IoT platform first, then attach parking and data-brokerage modules.',
    to_json(named_struct('domains', array('mobility', 'energy', 'surveillance', 'waste', 'environment'), 'platform_motion', true))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_kuala_lumpur_mobility',
    'Kuala Lumpur Urban Mobility',
    'MY',
    'Malaysia',
    'city',
    'intelligent_parking',
    'AI Urban Mobility and Parking Compliance',
    'public_sector_trigger',
    'Maxis Smart City Expo Public Reference',
    'my_maxis_ai_urban_mobility_001',
    'parking_and_access_regulation_signal',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.82 AS DOUBLE),
    'Reference includes urban mobility and automated vehicle identification for traffic, access, and parking regulation.',
    'https://www.maxis.com.my/en/about-maxis/newsroom/2025/september/maxis-powers-smarter-and-safer-cities-with-ai-urban-solutions-at-smart-city-expo-2025.html',
    'restricted_review_required',
    'Route through privacy review because automated identification can raise citizen-data concerns.',
    to_json(named_struct('automated_identification', true, 'parking_regulation', true, 'privacy_review_required', true))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_amata_chonburi',
    'AMATA City Chonburi',
    'TH',
    'Thailand',
    'industrial_zone',
    'connected_city_iot_platform',
    'Private 5G and Industrial Smart City IoT Platform',
    'csp_network',
    'AIS Business Public Reference',
    'th_ais_amata_5g_iot_001',
    '5g_iot_foundation',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.90 AS DOUBLE),
    'AIS positions 5G and IoT across NB-IoT, eMTC, LTE, fiber, and high-performance 5G use cases.',
    'https://www.ais.th/en/business/enterprise/technology-and-solution/5G-and-iot',
    'public',
    'Prioritize IoT platform and industrial-zone use cases before consumer city data products.',
    to_json(named_struct('network_capabilities', array('5G', 'NB-IoT', 'eMTC', 'fiber'), 'industrial_zone_fit', true))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_hcmc_iot_locality',
    'Ho Chi Minh City IoT Locality',
    'VN',
    'Vietnam',
    'city',
    'intelligent_parking',
    'NB-IoT Smart Parking and Environmental Monitoring',
    'csp_network',
    'Viettel Public Reference',
    'vn_viettel_nb_iot_smart_parking_001',
    'nb_iot_smart_parking_readiness',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.91 AS DOUBLE),
    'Reference describes NB-IoT coverage and use cases including smart parking, air quality, tracking, and metering.',
    'https://international.viettel.vn/news-detail/viettel-builds-hcm-city-the-first-iot-based-locality-in-vietnam',
    'public',
    'Rank intelligent parking and air-quality monitoring as first use cases.',
    to_json(named_struct('nb_iot_coverage', true, 'smart_parking', true, 'air_quality', true, 'metering', true))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_hcmc_iot_locality',
    'Ho Chi Minh City IoT Locality',
    'VN',
    'Vietnam',
    'city',
    'intelligent_parking',
    'NB-IoT Smart Parking and Environmental Monitoring',
    'municipal_open_data',
    'Synthetic HCMC Parking Operations Open Dataset',
    'vn_hcmc_parking_open_data_001',
    'parking_congestion_hotspot',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.84 AS DOUBLE),
    'Synthetic open-data profile shows recurring district-level parking pressure and curbside demand.',
    'synthetic://asean/vietnam/hcmc/parking-open-data',
    'public',
    'Confirm target districts and parking-operator ownership before account activation.',
    to_json(named_struct('parking_hotspots', 18, 'peak_occupancy_pct', 0.91, 'curbside_pressure', 'high'))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_hcmc_iot_locality',
    'Ho Chi Minh City IoT Locality',
    'VN',
    'Vietnam',
    'city',
    'intelligent_parking',
    'NB-IoT Smart Parking and Environmental Monitoring',
    'iot_telemetry',
    'Synthetic Parking Sensor Telemetry',
    'vn_hcmc_parking_sensor_telemetry_001',
    'sensor_estate_ready',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.86 AS DOUBLE),
    'Synthetic sensor estate shows sufficient device uptime and gateway health for a managed smart-parking pilot.',
    'synthetic://asean/vietnam/hcmc/parking-sensor-telemetry',
    'customer_permissioned',
    'Package parking sensor telemetry, NB-IoT connectivity, and operations dashboard into a pilot offer.',
    to_json(named_struct('sensor_count', 420, 'gateway_uptime_pct', 0.982, 'candidate_pilot_zones', 3))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_hcmc_iot_locality',
    'Ho Chi Minh City IoT Locality',
    'VN',
    'Vietnam',
    'city',
    'intelligent_parking',
    'NB-IoT Smart Parking and Environmental Monitoring',
    'public_sector_trigger',
    'Synthetic Urban Mobility Program Tracker',
    'vn_hcmc_mobility_program_trigger_001',
    'mobility_program_active',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.83 AS DOUBLE),
    'Synthetic public-sector trigger indicates an active mobility-improvement program aligned to parking and congestion outcomes.',
    'synthetic://asean/vietnam/hcmc/mobility-program-trigger',
    'public',
    'Route as activation-safe for CSP account planning with source refs and pilot constraints visible.',
    to_json(named_struct('program_domain', 'urban_mobility', 'budget_window', '2026', 'parking_kpi_present', true))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_metro_manila_iot',
    'Metro Manila IoT Platform Opportunity',
    'PH',
    'Philippines',
    'city',
    'connected_city_iot_platform',
    'City IoT Platform with Visualization and Analytics',
    'iot_telemetry',
    'PLDT Enterprise Public Reference',
    'ph_pldt_iot_platform_001',
    'iot_platform_cloud_analytics',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.86 AS DOUBLE),
    'Reference describes installed devices uploading data to cloud visualization, monitoring, and analytics through an IoT platform.',
    'https://pldtenterprise.com/enterprise/products/internet-of-things/smart-city',
    'customer_permissioned',
    'Map connected-device estate and prioritize platform consolidation.',
    to_json(named_struct('device_ingestion', true, 'visualization', true, 'monitoring', true, 'analytics', true))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_metro_manila_iot',
    'Metro Manila IoT Platform Opportunity',
    'PH',
    'Philippines',
    'city',
    'intelligent_parking',
    'Metro Manila Intelligent Parking and Curbside Intelligence',
    'municipal_open_data',
    'Synthetic Metro Manila Parking Open Dataset',
    'ph_manila_parking_open_data_001',
    'curbside_pressure_and_parking_demand',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.81 AS DOUBLE),
    'Synthetic parking pressure and occupancy indicators support an intelligent parking proposition but need operator confirmation.',
    'synthetic://asean/philippines/metro-manila/parking-open-data',
    'public',
    'Map MMDA and Manila Central Parking Operator stakeholders before CRM activation.',
    to_json(named_struct('target_b2b_customer_ids', array('b2b_ph_mmda_mobility_office', 'b2b_ph_manila_parking_operator'), 'parking_hotspots', 24, 'peak_occupancy_pct', 0.89, 'curbside_pressure', 'high'))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_metro_manila_iot',
    'Metro Manila IoT Platform Opportunity',
    'PH',
    'Philippines',
    'city',
    'intelligent_parking',
    'Metro Manila Intelligent Parking and Curbside Intelligence',
    'partner_ecosystem',
    'Synthetic Manila Partner Coverage',
    'ph_manila_parking_partner_001',
    'parking_operator_partner_available',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.80 AS DOUBLE),
    'Partner coverage improves feasibility but requires commercial validation before activation.',
    'synthetic://asean/philippines/metro-manila/parking-partner-coverage',
    'customer_permissioned',
    'Qualify Manila Central Parking Operator and Ayala Urban Property Group as pilot stakeholders.',
    to_json(named_struct('target_b2b_customer_ids', array('b2b_ph_manila_parking_operator', 'b2b_ph_ayala_property_group'), 'pilot_partner_count', 2, 'operator_route_available', true))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_metro_manila_iot',
    'Metro Manila IoT Platform Opportunity',
    'PH',
    'Philippines',
    'city',
    'intelligent_parking',
    'Metro Manila Intelligent Parking and Curbside Intelligence',
    'public_sector_trigger',
    'Synthetic Metro Manila Mobility Program Tracker',
    'ph_manila_mobility_trigger_001',
    'mobility_improvement_program',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.79 AS DOUBLE),
    'Public-sector trigger supports timing, but final pursuit should wait for account mapping and stakeholder validation.',
    'synthetic://asean/philippines/metro-manila/mobility-program-trigger',
    'public',
    'Route to review for account mapping and public-sector stakeholder validation.',
    to_json(named_struct('target_b2b_customer_ids', array('b2b_ph_mmda_mobility_office'), 'program_domain', 'urban_mobility', 'parking_kpi_present', true))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_metro_manila_iot',
    'Metro Manila IoT Platform Opportunity',
    'PH',
    'Philippines',
    'city',
    'urban_data_brokerage',
    'Metro Manila Mobility Insights and Data Brokerage',
    'mobility_data',
    'Synthetic Metro Manila Aggregated Mobility Dataset',
    'ph_metro_manila_mobility_data_001',
    'aggregated_mobility_insight_available',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.80 AS DOUBLE),
    'Aggregated mobility signals are commercially useful but must remain governed and non-personal.',
    'synthetic://asean/philippines/metro-manila/aggregated-mobility-data',
    'aggregated_anonymized',
    'Prepare a governed data-product review with aggregation and retention constraints.',
    to_json(named_struct('target_b2b_customer_ids', array('b2b_ph_mmda_mobility_office', 'b2b_ph_ayala_property_group'), 'data_product', 'mobility_insights', 'requires_privacy_review', true))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_metro_manila_iot',
    'Metro Manila IoT Platform Opportunity',
    'PH',
    'Philippines',
    'city',
    'urban_data_brokerage',
    'Metro Manila Mobility Insights and Data Brokerage',
    'data_marketplace',
    'Synthetic Philippines Urban Data Catalog',
    'ph_metro_manila_data_marketplace_001',
    'data_product_catalog_candidate',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.78 AS DOUBLE),
    'Marketplace readiness is promising but requires consent, access, and buyer-use policy checks.',
    'synthetic://asean/philippines/metro-manila/data-marketplace-catalog',
    'restricted_review_required',
    'Keep in governance review until data-product permissions and use cases are approved.',
    to_json(named_struct('target_b2b_customer_ids', array('b2b_ph_mmda_mobility_office', 'b2b_ph_ayala_property_group'), 'dataset_count', 9, 'consent_policy_required', true))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_metro_manila_iot',
    'Metro Manila IoT Platform Opportunity',
    'PH',
    'Philippines',
    'city',
    'connected_city_iot_platform',
    'City IoT Platform with Visualization and Analytics',
    'csp_network',
    'Synthetic CSP Network Readiness',
    'ph_metro_manila_iot_network_001',
    'iot_connectivity_ready',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.82 AS DOUBLE),
    'CSP network readiness plus IoT platform evidence supports a platform consolidation motion.',
    'synthetic://asean/philippines/metro-manila/csp-network-readiness',
    'customer_permissioned',
    'Assess candidate device estates for MMDA and Ayala Urban Property Group.',
    to_json(named_struct('target_b2b_customer_ids', array('b2b_ph_mmda_mobility_office', 'b2b_ph_ayala_property_group'), 'network_capabilities', array('5G', 'NB-IoT', 'fiber'), 'device_estate_candidate', true))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_metro_manila_iot',
    'Metro Manila IoT Platform Opportunity',
    'PH',
    'Philippines',
    'city',
    'connected_city_iot_platform',
    'City IoT Platform with Visualization and Analytics',
    'public_sector_trigger',
    'Synthetic Metro Manila IoT Program Tracker',
    'ph_metro_manila_iot_program_trigger_001',
    'platform_consolidation_trigger',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.79 AS DOUBLE),
    'A program trigger makes the platform motion timely but still requires account mapping.',
    'synthetic://asean/philippines/metro-manila/iot-program-trigger',
    'public',
    'Create review queue item for connected-city IoT platform stakeholder mapping.',
    to_json(named_struct('target_b2b_customer_ids', array('b2b_ph_mmda_mobility_office', 'b2b_ph_ayala_property_group'), 'platform_consolidation', true))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_singapore_smart_nation',
    'Singapore Smart Nation Urban Mobility',
    'SG',
    'Singapore',
    'city',
    'urban_data_brokerage',
    'Aggregated Mobility Insights and Data Brokerage',
    'data_marketplace',
    'Synthetic Urban Data Marketplace Catalog',
    'sg_urban_data_marketplace_001',
    'marketplace_dataset_available',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.80 AS DOUBLE),
    'Synthetic marketplace catalog shows mobility and parking-demand datasets that could be packaged as governed data products.',
    'synthetic://asean/singapore/urban-data-marketplace',
    'restricted_review_required',
    'Keep in review until aggregation, consent, data-retention, and buyer-use constraints are documented.',
    to_json(named_struct('dataset_count', 12, 'parking_demand_dataset', true, 'consent_policy_required', true))
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'asean_smart_city_proposition_readiness',
    'city_singapore_smart_nation',
    'Singapore Smart Nation Urban Mobility',
    'SG',
    'Singapore',
    'city',
    'urban_data_brokerage',
    'Aggregated Mobility Insights and Data Brokerage',
    'public_sector_trigger',
    'Synthetic Smart Mobility Planning Trigger',
    'sg_mobility_planning_trigger_001',
    'data_product_use_case_identified',
    timestamp('2026-04-27T00:00:00Z'),
    CAST(0.79 AS DOUBLE),
    'Synthetic planning trigger shows a public-sector need for corridor and parking-demand analytics.',
    'synthetic://asean/singapore/mobility-planning-trigger',
    'public',
    'Prepare a governed mobility-insights brief for stakeholder review, not direct activation.',
    to_json(named_struct('planning_domain', 'mobility', 'analytics_need', 'parking_and_corridor_demand'))
  )
AS source_rows(
  signal_pack_id,
  scenario_id,
  target_entity_id,
  target_entity_name,
  country_code,
  market,
  target_entity_type,
  offering_family,
  offer_bundle,
  source_family,
  source_system_name,
  signal_id,
  signal_type,
  signal_timestamp,
  signal_confidence,
  evidence_summary,
  evidence_url,
  consent_privacy_classification,
  recommended_next_action,
  source_payload
);

CREATE OR REPLACE VIEW pulse360_s4.bronze_smart_city.smart_city_b2b_customer_sample AS
SELECT *
FROM VALUES
  (
    'csp_smart_city_asean_foundation_20260427',
    'b2b_sg_lta_mobility_data_office',
    'Singapore Land Transport Authority Mobility Data Office',
    'SG',
    'Singapore',
    'transport_authority',
    'Public transport and urban mobility data stakeholder for Singapore Smart Nation propositions.',
    CAST(NULL AS STRING),
    array('urban_data_brokerage', 'intelligent_parking')
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'b2b_my_kl_parking_operator',
    'Kuala Lumpur Integrated Parking Operator',
    'MY',
    'Malaysia',
    'parking_operator',
    'Candidate operator for parking compliance, occupancy, and curbside intelligence.',
    CAST(NULL AS STRING),
    array('intelligent_parking')
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'b2b_th_amata_estate_operator',
    'AMATA Industrial Estate Operations',
    'TH',
    'Thailand',
    'industrial_estate_operator',
    'Industrial-zone operator for private 5G and connected city IoT platform expansion.',
    CAST(NULL AS STRING),
    array('connected_city_iot_platform')
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'b2b_vn_hcmc_parking_management',
    'Ho Chi Minh City Parking Management Authority',
    'VN',
    'Vietnam',
    'municipal_agency',
    'Municipal buyer for NB-IoT smart parking, environmental monitoring, and district pilot operations.',
    CAST(NULL AS STRING),
    array('intelligent_parking')
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'b2b_ph_mmda_mobility_office',
    'Metro Manila Development Authority Mobility Office',
    'PH',
    'Philippines',
    'transport_authority',
    'Metro Manila transport stakeholder for congestion, curbside, and multimodal data propositions.',
    CAST(NULL AS STRING),
    array('intelligent_parking', 'urban_data_brokerage')
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'b2b_ph_manila_parking_operator',
    'Manila Central Parking Operator',
    'PH',
    'Philippines',
    'parking_operator',
    'Commercial parking operator for occupancy, payment, enforcement, and curbside intelligence pilots.',
    CAST(NULL AS STRING),
    array('intelligent_parking')
  ),
  (
    'csp_smart_city_asean_foundation_20260427',
    'b2b_ph_ayala_property_group',
    'Ayala Urban Property Group',
    'PH',
    'Philippines',
    'property_group',
    'Private-sector venue and district owner for IoT platform, parking, and mobility data monetization.',
    CAST(NULL AS STRING),
    array('connected_city_iot_platform', 'intelligent_parking', 'urban_data_brokerage')
  )
AS customer_rows(
  signal_pack_id,
  b2b_customer_id,
  b2b_customer_name,
  country_code,
  market,
  customer_type,
  relationship_to_target,
  candidate_crm_account_id,
  priority_offering_families
);
