CREATE OR REPLACE VIEW pulse360_s4.bronze_proactive_signal.northstar_source_change_fixture AS
SELECT *
FROM VALUES
  (
    'fixture_northstar_proactive_signal_20260629',
    true,
    'Meridian Industrial Systems',
    'industrial manufacturing',
    'ASEAN',
    'grp_northstar_foods',
    'Northstar Foods Group',
    array('ID', 'TH', 'SG', 'PH'),
    'anchored',
    'run_proactive_signal_demo_20260629',
    'evt_product_installed_base_id_20260629_001',
    'product_telemetry',
    'synthetic_installed_base_feed',
    'installed_base_event',
    timestamp('2026-06-29T01:00:00Z'),
    'northstar-foods-id-plant-07',
    'New Indonesia plant line detected with six connected assets and no linked maintenance plan.',
    'Installed base is expanding faster than service coverage.',
    to_json(named_struct(
      'asset_count', 6,
      'site_country', 'ID',
      'coverage_status', 'missing_maintenance_plan'
    )),
    array('src_installed_base_id_plant_07')
  ),
  (
    'fixture_northstar_proactive_signal_20260629',
    true,
    'Meridian Industrial Systems',
    'industrial manufacturing',
    'ASEAN',
    'grp_northstar_foods',
    'Northstar Foods Group',
    array('ID', 'TH', 'SG', 'PH'),
    'anchored',
    'run_proactive_signal_demo_20260629',
    'evt_service_warranty_id_20260629_002',
    'service',
    'synthetic_service_warranty_feed',
    'warranty_expiring',
    timestamp('2026-06-29T01:15:00Z'),
    'northstar-foods-id-plant-07',
    'Warranty for the primary packing line expires in 45 days.',
    'Seller should engage before warranty expiry creates service risk.',
    to_json(named_struct(
      'warranty_days_remaining', 45,
      'asset_family', 'packing_line',
      'site_country', 'ID'
    )),
    array('src_warranty_id_pack_line_45d')
  ),
  (
    'fixture_northstar_proactive_signal_20260629',
    true,
    'Meridian Industrial Systems',
    'industrial manufacturing',
    'ASEAN',
    'grp_northstar_foods',
    'Northstar Foods Group',
    array('ID', 'TH', 'SG', 'PH'),
    'anchored',
    'run_proactive_signal_demo_20260629',
    'evt_erp_contract_id_20260629_003',
    'erp',
    'synthetic_contract_entitlement_feed',
    'no_active_contract',
    timestamp('2026-06-29T01:30:00Z'),
    'northstar-foods-id-plant-07',
    'No active maintenance contract found for the Indonesia plant account or known subsidiaries.',
    'Coverage gap is commercially actionable and not just a data quality issue.',
    to_json(named_struct(
      'active_contract_count', 0,
      'contract_family', 'maintenance',
      'coverage_scope', 'group_and_known_subsidiaries'
    )),
    array('src_contract_gap_id_plant_07')
  ),
  (
    'fixture_northstar_proactive_signal_20260629',
    true,
    'Meridian Industrial Systems',
    'industrial manufacturing',
    'ASEAN',
    'grp_northstar_foods',
    'Northstar Foods Group',
    array('ID', 'TH', 'SG', 'PH'),
    'anchored',
    'run_proactive_signal_demo_20260629',
    'evt_partner_spares_th_20260629_004',
    'partner',
    'synthetic_distributor_order_feed',
    'spare_parts_spike',
    timestamp('2026-06-29T02:00:00Z'),
    'northstar-foods-th-distributor-a',
    'Thailand distributor orders for replacement belts increased by 38 percent in the last 30 days.',
    'Regional wear pattern suggests preventive maintenance opportunity across the group.',
    to_json(named_struct(
      'part_family', 'replacement_belts',
      'order_delta_pct', 0.38,
      'site_country', 'TH'
    )),
    array('src_partner_spares_th_belts')
  ),
  (
    'fixture_northstar_proactive_signal_20260629',
    true,
    'Meridian Industrial Systems',
    'industrial manufacturing',
    'ASEAN',
    'grp_northstar_foods',
    'Northstar Foods Group',
    array('ID', 'TH', 'SG', 'PH'),
    'anchored',
    'run_proactive_signal_demo_20260629',
    'evt_crm_duplicate_sg_20260629_005',
    'crm',
    'synthetic_salesforce_account_feed',
    'duplicate_subsidiary_candidate',
    timestamp('2026-06-29T02:20:00Z'),
    'northstar-foods-sg-procurement',
    'Singapore procurement account appears as a duplicate subsidiary with partial hierarchy coverage.',
    'Recommended action should route stewardship before any group-level CRM writeback.',
    to_json(named_struct(
      'duplicate_confidence', 0.81,
      'site_country', 'SG',
      'stewardship_required', true
    )),
    array('src_crm_duplicate_sg_procurement')
  ),
  (
    'fixture_northstar_proactive_signal_20260629',
    true,
    'Meridian Industrial Systems',
    'industrial manufacturing',
    'ASEAN',
    'grp_northstar_foods',
    'Northstar Foods Group',
    array('ID', 'TH', 'SG', 'PH'),
    'anchored',
    'run_proactive_signal_demo_20260629',
    'evt_service_cases_ph_20260629_006',
    'service',
    'synthetic_case_management_feed',
    'service_case_increase',
    timestamp('2026-06-29T02:45:00Z'),
    'northstar-foods-ph-cold-chain',
    'Philippines cold-chain service cases increased from two to seven in the last quarter.',
    'Case trend strengthens the preventive maintenance signal across ASEAN subsidiaries.',
    to_json(named_struct(
      'previous_quarter_case_count', 2,
      'current_quarter_case_count', 7,
      'site_country', 'PH'
    )),
    array('src_service_cases_ph_cold_chain')
  )
AS source_rows(
  fixture_id,
  synthetic_flag,
  customer_name,
  customer_industry,
  customer_region,
  group_entity_id,
  group_name,
  country_scope,
  crm_anchor_status,
  simulation_run_id,
  source_event_id,
  source_family,
  source_system,
  source_event_type,
  event_timestamp,
  entity_key,
  change_summary,
  impact_hint,
  source_payload,
  source_refs
);
