CREATE OR REPLACE VIEW pulse360_s4.gold_proactive_signal.datacloud_proactive_signal_projection AS
SELECT
  'ent_northstar_foods_group' AS canonical_account_id,
  'ent_northstar_foods_group' AS entity_id,
  source_account_id,
  'northstar_foods_group|asean|maintenance_gap' AS deterministic_key,
  account_name,
  CAST(82 AS DOUBLE) AS duplicate_confidence,
  CAST(NULL AS STRING) AS hierarchy_parent_id,
  'ent_northstar_foods_group' AS hierarchy_child_id,
  CAST(91 AS DOUBLE) AS validity_score,
  false AS review_flag,
  'up_northstar_foods_group' AS unified_profile_id,
  CAST(94 AS DOUBLE) AS identity_confidence,
  to_json(named_struct(
    'group_entity_id', group_entity_id,
    'group_name', group_name,
    'country_scope', country_scope,
    'crm_anchor_status', crm_anchor_status,
    'source_account_id', source_account_id
  )) AS hierarchy_payload,
  intent_signal_payload,
  CAST(NULL AS DOUBLE) AS group_revenue_rollup,
  CAST(78 AS DOUBLE) AS cross_sell_propensity,
  CAST(64 AS DOUBLE) AS health_score,
  coverage_gap_flag,
  CAST(12 AS DOUBLE) AS competitor_risk_signal,
  'Industrial Service Maintenance' AS primary_brand_name,
  CAST(6 AS BIGINT) AS active_product_count,
  CAST(73 AS DOUBLE) AS engagement_intensity_score,
  CAST(0 AS BIGINT) AS open_opportunity_count,
  CAST(NULL AS TIMESTAMP) AS last_engagement_timestamp,
  run_timestamp AS last_synced_timestamp,
  'Northstar Foods Group' AS external_legal_name,
  CAST(NULL AS STRING) AS external_registration_number,
  false AS is_externally_validated,
  CAST(NULL AS DOUBLE) AS validity_score_external,
  CAST(4 AS BIGINT) AS external_subsidiaries_found,
  ai_narrative,
  ai_recommended_actions,
  run_timestamp AS ai_narrative_generated_at,
  run_id AS enrichment_run_id,
  CAST(86 AS DOUBLE) AS regulatory_readiness_score,
  CAST(1 AS BIGINT) AS duplicate_exposure_count,
  CAST(4 AS BIGINT) AS group_known_subsidiary_count,
  CAST(2 AS BIGINT) AS crm_covered_subsidiary_count,
  CAST(NULL AS DOUBLE) AS group_revenue_visible,
  false AS external_revenue_confirmed,
  'proactive-signal-fixture' AS model_id,
  'pulse360-proactive-signal-demo-v1' AS prompt_version,
  to_json(source_refs) AS source_refs,
  CAST(size(source_refs) AS BIGINT) AS citation_count,
  'Databricks Proactive Signal - Last ingested: 2026-06-29T03:00:00Z' AS ingestion_metadata_label,
  agentforce_execution_policy,
  run_id,
  run_ts,
  run_timestamp,
  model_version
FROM pulse360_s4.silver_proactive_signal.northstar_proactive_account_signal;
