CREATE OR REPLACE VIEW pulse360_s4.silver_salesforce.crm_governance_case AS
WITH bronze AS (
  SELECT
    *,
    to_json(struct(*)) AS bronze_payload
  FROM pulse360_s4.bronze_salesforce.governance_case__c
  WHERE COALESCE(IsDeleted, false) = false
)
SELECT
  Id AS crm_governance_case_id,
  Name AS crm_governance_case_name,
  OwnerId AS crm_owner_id,
  Status__c AS governance_case_status,
  Priority__c AS governance_case_priority,
  Decision_Status__c AS decision_status,
  Recommended_Action__c AS recommended_action,
  Decision_Reason_Code__c AS decision_reason_code,
  Decision_Reason_Text__c AS decision_reason_text,
  Decided_At__c AS decided_at,
  Decided_By__c AS decided_by_user_id,
  Downstream_Update_Status__c AS downstream_update_status,
  Merge_Execution_Status__c AS merge_execution_status,
  Merge_Executed_At__c AS merge_executed_at,
  Merge_Executed_By__c AS merge_executed_by_user_id,
  get_json_object(bronze_payload, '$.Source_Product__c') AS source_product,
  get_json_object(bronze_payload, '$.Data_Cloud_Review_Queue_Id__c') AS data_cloud_review_queue_id,
  get_json_object(bronze_payload, '$.Data_Cloud_Source_Record_Id__c') AS data_cloud_source_record_id,
  get_json_object(bronze_payload, '$.Target_Entity_Name__c') AS target_entity_name,
  get_json_object(bronze_payload, '$.Country_Code__c') AS country_code,
  get_json_object(bronze_payload, '$.Market__c') AS market,
  get_json_object(bronze_payload, '$.Offering_Family__c') AS offering_family,
  get_json_object(bronze_payload, '$.Offer_Bundle__c') AS offer_bundle,
  get_json_object(bronze_payload, '$.Target_B2B_Customer_Ids__c') AS target_b2b_customer_ids,
  get_json_object(bronze_payload, '$.Target_B2B_Customer_Names__c') AS target_b2b_customer_names,
  get_json_object(bronze_payload, '$.Recommended_Next_Actions__c') AS recommended_next_actions,
  get_json_object(bronze_payload, '$.Review_Priority__c') AS review_priority,
  get_json_object(bronze_payload, '$.Activation_Block_Reasons__c') AS activation_block_reasons,
  Candidate_Pair_Id__c AS candidate_pair_id,
  Left_Account__c AS left_account_id,
  Right_Account__c AS right_account_id,
  Merged_Account__c AS merged_account_id,
  Surviving_Account__c AS surviving_account_id,
  try_cast(Duplicate_Confidence__c AS DOUBLE) AS duplicate_confidence,
  Confidence_Band__c AS confidence_band,
  try_cast(Review_Flag__c AS BOOLEAN) AS review_flag,
  try_cast(Review_Followup_Required__c AS BOOLEAN) AS review_followup_required,
  try_cast(Hierarchy_Conflict_Flag__c AS BOOLEAN) AS hierarchy_conflict_flag,
  Hierarchy_Impact_Summary__c AS hierarchy_impact_summary,
  Evidence_Run_Id__c AS evidence_run_id,
  Evidence_Run_Timestamp__c AS evidence_run_timestamp,
  Source_Snapshot_Id__c AS source_snapshot_id,
  Model_Version__c AS model_version,
  Audit_Event_Id__c AS audit_event_id,
  Attribute_Validity_Payload__c AS attribute_validity_payload,
  Feature_Explanations__c AS feature_explanations,
  Top_Match_Features__c AS top_match_features,
  CreatedDate AS crm_created_at,
  LastModifiedDate AS crm_last_modified_at,
  SystemModstamp AS crm_system_modstamp,
  'salesforce' AS source_system
FROM bronze;
