CREATE OR REPLACE VIEW pulse360_s4.bronze_enterprise_sources.synthetic_enterprise_source_sample AS
SELECT *
FROM VALUES
  (
    'synthetic_pack_revops_foundation_20260426',
    'priority1_account_intelligence_cycle',
    true,
    'pulse360-priority1-seed-20260426',
    'erp_invoice_apac_001',
    'erp',
    'Synthetic ERP Billing',
    'acct_global_medical_asia',
    '001dL00000SYN001QAA',
    'invoice_posted',
    timestamp('2026-04-20T09:15:00Z'),
    'INV-APAC-10001',
    CAST(0.94 AS DOUBLE),
    to_json(named_struct(
      'billing_entity', 'Global Medical Asia Pte Ltd',
      'product_family', 'Revenue Cloud',
      'invoice_amount_usd', 185000,
      'payment_status', 'paid'
    )),
    array('billing_entity_name_differs_from_crm_account'),
    'ent_global_medical_asia',
    'review_required'
  ),
  (
    'synthetic_pack_revops_foundation_20260426',
    'priority1_account_intelligence_cycle',
    true,
    'pulse360-priority1-seed-20260426',
    'epm_forecast_apac_001',
    'epm',
    'Synthetic EPM Forecast',
    'acct_global_medical_asia',
    '001dL00000SYN001QAA',
    'forecast_gap_detected',
    timestamp('2026-04-21T03:00:00Z'),
    'FCAST-APAC-Q2-10001',
    CAST(0.90 AS DOUBLE),
    to_json(named_struct(
      'territory', 'APAC Health',
      'plan_amount_usd', 1200000,
      'forecast_amount_usd', 850000,
      'coverage_gap_usd', 350000
    )),
    array('coverage_gap_requires_cross_source_confirmation'),
    'ent_global_medical_asia',
    'review_required'
  ),
  (
    'synthetic_pack_revops_foundation_20260426',
    'priority1_account_intelligence_cycle',
    true,
    'pulse360-priority1-seed-20260426',
    'support_case_apac_001',
    'support',
    'Synthetic Support Cloud',
    'acct_global_medical_asia',
    '001dL00000SYN001QAA',
    'sla_breach',
    timestamp('2026-04-22T14:30:00Z'),
    'CASE-APAC-7788',
    CAST(0.88 AS DOUBLE),
    to_json(named_struct(
      'severity', 'high',
      'sla_breach_hours', 11,
      'affected_product', 'Service Cloud',
      'renewal_risk_hint', 'medium'
    )),
    array('negative_signal_should_temper_expansion_action'),
    'ent_global_medical_asia',
    'review_required'
  ),
  (
    'synthetic_pack_revops_foundation_20260426',
    'priority1_account_intelligence_cycle',
    true,
    'pulse360-priority1-seed-20260426',
    'contract_renewal_apac_001',
    'contracts',
    'Synthetic Contract Repository',
    'acct_global_medical_asia',
    '001dL00000SYN001QAA',
    'renewal_window_open',
    timestamp('2026-04-19T00:00:00Z'),
    'CTR-APAC-2026-04',
    CAST(0.93 AS DOUBLE),
    to_json(named_struct(
      'renewal_date', '2026-07-31',
      'contract_value_usd', 920000,
      'auto_renewal', false,
      'co_termination_candidate', true
    )),
    array('renewal_action_depends_on_support_risk'),
    'ent_global_medical_asia',
    'review_required'
  ),
  (
    'synthetic_pack_revops_foundation_20260426',
    'priority1_account_intelligence_cycle',
    true,
    'pulse360-priority1-seed-20260426',
    'telemetry_usage_apac_001',
    'product_telemetry',
    'Synthetic Product Telemetry',
    'acct_global_medical_asia',
    '001dL00000SYN001QAA',
    'adoption_increase',
    timestamp('2026-04-23T08:00:00Z'),
    'USAGE-APAC-001',
    CAST(0.91 AS DOUBLE),
    to_json(named_struct(
      'active_users_30d', 640,
      'active_users_delta_pct', 0.22,
      'feature_family', 'case deflection',
      'feature_exposure_pct', 0.68
    )),
    array('adoption_supports_expansion_but_not_without_contract_context'),
    'ent_global_medical_asia',
    'review_required'
  ),
  (
    'synthetic_pack_revops_foundation_20260426',
    'priority1_account_intelligence_cycle',
    true,
    'pulse360-priority1-seed-20260426',
    'intent_campaign_apac_001',
    'marketing_intent',
    'Synthetic Marketing Intent',
    'acct_global_medical_asia',
    '001dL00000SYN001QAA',
    'topic_surge',
    timestamp('2026-04-24T05:00:00Z'),
    'INTENT-APAC-AI-001',
    CAST(0.77 AS DOUBLE),
    to_json(named_struct(
      'topic', 'AI service automation',
      'engagement_score', 82,
      'campaign_members', 6,
      'buying_committee_hint', 'service operations'
    )),
    array('intent_signal_lower_reliability_than_system_of_record'),
    'ent_global_medical_asia',
    'review_required'
  ),
  (
    'synthetic_pack_revops_foundation_20260426',
    'priority1_account_intelligence_cycle',
    true,
    'pulse360-priority1-seed-20260426',
    'hierarchy_internal_apac_001',
    'internal_hierarchy',
    'Synthetic Enterprise Master Data',
    'acct_global_medical_asia',
    '001dL00000SYN001QAA',
    'subsidiary_mapping',
    timestamp('2026-04-18T00:00:00Z'),
    'HIER-GLOBAL-MED-ASIA',
    CAST(0.96 AS DOUBLE),
    to_json(named_struct(
      'ultimate_parent', 'Global Medical Holdings',
      'regional_parent', 'Global Medical Asia Pte Ltd',
      'subsidiary_count', 4,
      'crm_covered_subsidiary_count', 2
    )),
    array('subsidiary_gap_should_create_stewardship_review'),
    'ent_global_medical_asia',
    'review_required'
  )
AS source_rows(
  source_pack_id,
  scenario_id,
  synthetic_flag,
  generation_seed,
  source_record_id,
  source_family,
  source_system_name,
  entity_key,
  crm_account_id,
  event_type,
  event_timestamp,
  business_object_id,
  source_confidence,
  source_payload,
  edge_case_tags,
  expected_resolved_entity_id,
  expected_activation_state
);
