CREATE OR REPLACE TABLE pulse360_s4.intelligence.datacloud_export_accounts AS
SELECT
  canonical_account_id,
  canonical_account_id AS entity_id,
  source_account_id,
  deterministic_key,
  account_name,
  CAST(identity_confidence AS DOUBLE) AS duplicate_confidence,
  parent_account_id AS hierarchy_parent_id,
  canonical_account_id AS hierarchy_child_id,
  CAST(validity_score AS DOUBLE) AS validity_score,
  CASE WHEN validity_score < 85 THEN true ELSE false END AS review_flag,
  unified_profile_id,
  CAST(identity_confidence AS DOUBLE) AS identity_confidence,
  hierarchy_payload,
  intent_signal_payload,
  group_revenue_rollup,
  cross_sell_propensity,
  health_score,
  coverage_gap_flag,
  competitor_risk_signal,
  primary_brand_name,
  active_product_count,
  engagement_intensity_score,
  open_opportunity_count,
  last_engagement_timestamp,
  last_synced_timestamp,
  external_legal_name,
  external_registration_number,
  is_externally_validated,
  validity_score_external,
  external_subsidiaries_found,
  ai_narrative,
  ai_recommended_actions,
  ai_narrative_generated_at,
  enrichment_run_id,
  regulatory_readiness_score,
  duplicate_exposure_count,
  group_known_subsidiary_count,
  crm_covered_subsidiary_count,
  group_revenue_visible,
  external_revenue_confirmed,
  model_id,
  prompt_version,
  source_refs,
  citation_count,
  ingestion_metadata_label,
  run_id,
  run_ts,
  run_timestamp,
  model_version
FROM pulse360_s4.gold.account_export_base;
